### ISSUE TITLE
NTR: Request for S05 eddy covariance method (BODCNVS-339)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S05#5]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>eddy covariance method <p><b>Definition</b><p> A method for measuring exchanges of heat, mass, and momentum between a flat, horizontally homogeneous surface and the overlying atmosphere was proposed by Montgomery (1948), Swinbank (1951), and Obukhov 1951).<p><H2> Optional </H2><p><b>Sources/references</b><p> https://link.springer.com/chapter/10.1007%2F978-94-007-2351-1_1<p> <b>ORCID</b><p> roswri<p>

**Comment by gwemon** [comment]
In order to be consistent with the existing content in S05 I am proposing to change the preferred label slightly to be: "computation using the eddy covariance method"
And also to give a more generic definition adapted the one provided and from Wikipedia entry (https://en.wikipedia.org/wiki/Eddy_covariance) e.g.:
"A statistical method used to process eddy covariance measurements and derive quantities such as heat, momentum, and gas fluxes between a flat, horizontally homogeneous surface and the overlying atmosphere."

**Comment by gwemon** [comment]
Hi Roseanna,
Which BODCNVS ticket is this related to?

________________________________________

**Comment by roswri** [comment]
Hi Gwen,

I accept your proposals, and it's related to https://jira.ceh.ac.uk/browse/BODCNVS-339

Thanks,
Roseanna

**Comment by gwemon** [comment]
Code S050230 has been queued for publication.

**Comment by gwemon** [comment]
http://vocab.nerc.ac.uk/collection/S05/current/S050230/
